plugins:
  - jekyll-paginate
  - jekyll-sitemap

sass:
  sass_dir: _sass
  style: compressed

timezone: US/CT
locale: "en-US"
title: "self.randomize()"
url: "https://ngpham.github.io"

permalink: /:year/:month/:day/:title/

paginate: 5
paginate_path: "page:num"

# config for jekyll-paginate-v2, not supported yet on github
# pagination:
#   enabled: true
#   per_page: 5
#   permalink: '/page/:num/'
#   title: ':title - page :num of :max'
#   limit: 0
#   sort_field: 'date'
#   sort_reverse: true

disqus:
  shortname: "ngpham"

include:
  - _pages

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false
